### ISSUE TITLE
Doesn't like my files

### ISSUE THREAD

**Issue by bryc** [stormshield/HiveSwarming#1]
I'm trying to use this to modify the RegHive file that is created by [Sandboxie ](https://sandboxie-plus.com/)(software which creates a sandboxed environment).  I've used an app called [RegFileExport ](https://www.nirsoft.net/utils/registry_file_offline_export.html)which successfully creates a .reg file, but it cannot convert back to a hive. And HiveSwarming doesn't work for these files.

Here's the error I get when trying to go Hive>Reg:

```
Opening subkey named classes at index 1 - Current key name: software:
ERROR 80070005 (Access is denied. )

Getting contents of subkey named software - Current key name: current:
ERROR 80070005 (Access is denied. )

Getting contents of subkey named current - Current key name: user:
ERROR 80070005 (Access is denied. )

Getting contents of subkey named user - Current key name: (HiveRoot):
ERROR 80070005 (Access is denied. )
```

Also, the .reg file that RegFileExport creates cannot be converted into a RegHive file.

Here's the error:

```
Reading key beginning with prefix <empty> - Line does not begin with opening bracket:
ERROR 8000ffff (Catastrophic failure )

Serializing registry fileOutput.REG:
ERROR 8000ffff (Catastrophic failure )
```

Here's the first few lines of that .reg file:

```
Windows Registry Editor Version 5.00


[]

[machine]

[machine\software]

[machine\software\classes]

[machine\software\classes\clsid]

```

I tried removing the `[]` line, and got even more errors:

```
Value name S-1-5-21-2296009262-2775004226-3358008871-1001 - Expecting two hexadecimal digits:
ERROR 8000ffff (Catastrophic failure )

Reading key machine\software\WOW6432Node\Google\Update\ClientStateMedium\{8A000345-D504-403C-A0F1-A69D9E000F96}\LastWasDefault - Could not read values:
ERROR 8000ffff (Catastrophic failure )

Checking if there are keys beginning with machine\software\WOW6432Node\Google\Update\ClientStateMedium\{8A000345-D504-403C-A0F1-A69D9E000F96}\:
ERROR 8000ffff (Catastrophic failure )

Checking if there are keys beginning with machine\software\WOW6432Node\Google\Update\ClientStateMedium\:
ERROR 8000ffff (Catastrophic failure )

Checking if there are keys beginning with machine\software\WOW6432Node\Google\Update\:
ERROR 8000ffff (Catastrophic failure )

Checking if there are keys beginning with machine\software\WOW6432Node\Google\:
ERROR 8000ffff (Catastrophic failure )

Checking if there are keys beginning with machine\software\WOW6432Node\:
ERROR 8000ffff (Catastrophic failure )

Checking if there are keys beginning with machine\software\:
ERROR 8000ffff (Catastrophic failure )

Checking if there are keys beginning with machine\:
ERROR 8000ffff (Catastrophic failure )

Serializing registry fileOutput2.REG:
ERROR 8000ffff (Catastrophic failure )
```

**Comment by salsifis** [comment]
Hello

In this first answer I will focus on the reg to hive conversion.

There are three problems that are encountered here:

1. There are two empty lines after the preamble (there should be a single empty line)
2. There are multiple roots in the hive (`machine` and `user`). Try to edit the registry file and to replace `[]` with `[ROOT]`, all instances of `[machine` with `[ROOT\machine`, and all instances of `[user` by `[ROOT\user`
2. Hexadecimal representations are not indented by two leading spaces in the continuation lines. The exported `.reg` file is not conformant to what `reg.exe` produces itself, and HiveSwarming is not really lax about that.

The following image shows what you can modify in your `reg` file for it to work with the current version of HiveSwarming.

![image](https://user-images.githubusercontent.com/1233345/155083783-2ee0071c-4409-4dbd-9dfa-aafdec978423.png)

I will try to fix those problems by Accepting an empty root name and relaxing parsing of the reg file.

**Comment by salsifis** [comment]
In the second answer, I focus on the first problem: exporting a hive to a reg file.

The problem here is that you have the key `user\current\software\classes` that is a symbolic link (the registry key has a special flag, and there is a special value named `SymbolicLinkValue`). Registry symbolic links are not currently supported by this version of Hiveswarming. There is probably no “correct” way to support them, but at least we could try to not fail when encountering a symlink.

I will also try to fix this soon.

**Comment by salsifis** [comment]
Hello.

Version 1.2 should fix the problem with symbolic links.

You can use HiveSwarming as a unique tool to convert from hive to .reg back and forth.

Please note that during the testing of this fix, I identified a bug in RegFileExport, which is that backslashes (`\`) in value names are not properly escaped while generating the *.reg* output.
