### ISSUE TITLE
Unable to convert .reg to hive format

### ISSUE THREAD

**Issue by Explolt** [stormshield/HiveSwarming#2]
I'm trying to convert a .reg file with the header of **Windows Registry Editor Version 5.00**

This is the command usage I am using and the following error.
```
HiveSwarming.exe --reg-file-to-hive file.reg newfile
File file.reg preamble not found:
ERROR 8000ffff (Catastrophic failure )

Serializing registry filefile.reg:
ERROR 8000ffff (Catastrophic failure )
```

**Comment by salsifis** [comment]
Hello,

Hiveswarming expects the following and is quite strict:
* The file has a byte order mark for UTF-16, Little Endian (so, its hex dump begins with FF FE)
* After the BOM, The file begins with “Windows Registry Editor Version 5.0.0” and two CR+LF.

Altogether your reg file must have the following hexadecimal preamble:

```
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ ff fe 57 00 69 00 6e 00 ┊ 64 00 6f 00 77 00 73 00 │××W⋄i⋄n⋄┊d⋄o⋄w⋄s⋄│
│00000010│ 20 00 52 00 65 00 67 00 ┊ 69 00 73 00 74 00 72 00 │ ⋄R⋄e⋄g⋄┊i⋄s⋄t⋄r⋄│
│00000020│ 79 00 20 00 45 00 64 00 ┊ 69 00 74 00 6f 00 72 00 │y⋄ ⋄E⋄d⋄┊i⋄t⋄o⋄r⋄│
│00000030│ 20 00 56 00 65 00 72 00 ┊ 73 00 69 00 6f 00 6e 00 │ ⋄V⋄e⋄r⋄┊s⋄i⋄o⋄n⋄│
│00000040│ 20 00 35 00 2e 00 30 00 ┊ 30 00 0d 00 0a 00 0d 00 │ ⋄5⋄.⋄0⋄┊0⋄_⋄_⋄_⋄│
│00000050│ 0a 00                   ┊                         │_⋄      ┊        │
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
```

Could you please check that your file is conformant?

If this is the case, could you attach it or try to reproduce with a smaller file and attach it?

**Comment by salsifis** [comment]
Hello @Explolt
Is the issue solved for you?
Thank you

**Comment by salsifis** [comment]
In the absence of response, I close this issue.
